Lif 4
Life-Science-Project/LifeScience pull request #1
Opened 2021-03-27 10:05 UTC by rorione

Base class structure created and ready to refactoring)

2021-03-27 16:47 UTC, avpotapov00 requested changes
Итого: создавать сохраняемые объекты должны фабрики, мапперы должны быть компонентами и их методы должны быть не статическими, по тестам нужно отдельно созвониться, но в целом структура теста оставлена в комментариях + все замечания в комментариях.

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/article/service/ArticleServiceImpl.kt
> +class ArticleServiceImpl @Autowired constructor(
можно сократить до «class ArticleServiceImpl (…» - будет работать аналогично
(те убрать "@Autowired constructor")

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/article/view/ArticleViewMapper.kt
> +class ArticleViewMapper {
Сделать компонентом (@Component) и метод не статическим

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/method/MethodController.kt
> +    @PostMapping("")
Сделать просто @PostMapping - эквивалентно

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/method/MethodController.kt
> +    @GetMapping("/test")
Удалить

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/method/dto/MethodDTO.kt
> +    val sectionID: Long,
Сделать @NotNull

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/method/dto/MethodDTO.kt
> +    val articleDTO: ArticleDTO
Убрать: будет создаваться отдельным запросом или по шаблону дефолтный

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/method/dto/MethodDTOToInfoWrapper.kt
> +class MethodDTOToInfoWrapper(private val methodDTO: MethodDTO) : MethodInfo {
MethodDTOToInfoWrapper следует переименовать в MethodDTOInfoAdapter - тк это паттерн адаптер)

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/method/dto/MethodDTOToInfoWrapper.kt
> +        return 0
Тут такое не пойдет, для  DTO, которые приходят на создание, id будет null, тк объект еще не создан. Убрать захардкоженый 0 во всех адаптерах и сделать null везде, где id еще нет

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/method/service/MethodServiceImpl.kt
> +class MethodServiceImpl @Autowired constructor(
убрать лишние "@Autowired contructor"

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/method/view/MethodViewMapper.kt
> +class MethodViewMapper {
Сделать просто компонентом (@Component), а метод не статическим

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/section/SectionController.kt
>      @GetMapping("/test")
Удалить

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/section/dto/SectionDTOToInfoWrapper.kt
> +class SectionDTOToInfoWrapper (private val sectionDTO: SectionDTO) : SectionInfo {
SectionDTOToInfoWrapper следует переименовать в SectionDTOInfoAdapter - тк это паттерн адаптер)

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/section/dto/SectionDTOToInfoWrapper.kt
> +        return 0
Убрать захардкоженный 0, когда у нас еще нет id для только что созданной сущности, id = null

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/section/service/SectionServiceImpl.kt
> +class SectionServiceImpl @Autowired constructor(
Убрать лишние "@Autowired constructor"

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/section/view/SectionViewMapper.kt
> +class SectionViewMapper {
Сделать @Component и метод не статическим

2021-03-27 16:47 UTC, avpotapov00 commented on src/test/kotlin/com/jetbrains/life_science/MethodControllerTests.kt
> +class MethodControllerTests @Autowired constructor(val mockMvc : MockMvc){
не очень понятно что тестирует этот класс

2021-03-27 16:47 UTC, avpotapov00 commented on src/test/kotlin/com/jetbrains/life_science/MethodServiceTests.kt
> +            .`when`(articleService.addArticle(any(ArticleInfo::class.java)))
вызов функции when возможет без кавычек

2021-03-27 16:47 UTC, avpotapov00 commented on src/test/kotlin/com/jetbrains/life_science/MethodServiceTests.kt
> +    fun methodAdd() {
перед тестом следует добавлять комментарии - что тестируем, что имеем на входе и какое поведение ожидаем на выходе

2021-03-27 16:47 UTC, avpotapov00 commented on src/test/kotlin/com/jetbrains/life_science/MethodServiceTests.kt
> +        methodService.addMethod(methodInfo)
отсутствуют проверки на итоговое состояние системы (assert, verify)

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/article/service/ArticleServiceImpl.kt
> +        return articleRepository.save(Article(articleInfo.getId()))
Созданием сохраняемых объектов должны заниматься фабрики: MethodFactory, SectionFactor, ArticleFactory

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/method/service/MethodServiceImpl.kt
> +        val method = Method(methodInfo.getId(), methodInfo.getName(), section, article)
Созданием сохраняемых объектов должны заниматься фабрики: MethodFactory, SectionFactor, ArticleFactory

2021-03-27 16:47 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/section/service/SectionServiceImpl.kt
> +        sectionRepository.save(Section(sectionInfo.getID(), sectionInfo.getName(), parent))
Созданием сохраняемых объектов должны заниматься фабрики: MethodFactory, SectionFactor, ArticleFactory

2021-03-27 22:06 UTC, andrey-star approved these changes
nice job

Если планируем реализовать какую-то часть позже, давайте добавлять issue и комментарий `// TODO(<issue_number>): <comment>`, например: `// TODO(#34): implement tests`
И конечно давайте дифф поменьше в следующий раз, тяжко ревьюить

2021-03-28 13:42 UTC, avpotapov00 approved these changes

2021-03-28 13:44 UTC, merged