Sections tests
Life-Science-Project/LifeScience pull request #155
Opened 2021-05-04 19:11 UTC by Borodin239

2021-05-04 20:03 UTC, andrey-star requested changes
* Principal не может быть null
* checkAccess взять из других контроллеров, в соответствии поправить адвайс
* Не покрыты Parameters секций

2021-05-05 09:23 UTC, avpotapov00 requested changes
В целом большие тесты следует разделить на логические блоки создания тестовых данных, создания ожидаемых данных, действие и проверки, которые нужно пометить комментариями. Пример смотри в моих тестах контроллера версий статьи.

2021-05-05 09:23 UTC, avpotapov00 commented on backend/src/test/kotlin/com/jetbrains/life_science/section/SectionControllerTest.kt
> +            assertEquals(section.articleVersionId, 1)
нужно проверять на соответствие не только id-шник, но и все поля полученных секций

2021-05-05 09:23 UTC, avpotapov00 commented on backend/src/test/kotlin/com/jetbrains/life_science/section/SectionControllerTest.kt
> +        createSection(1, sectionDTO)
используется только в этом тесте, внести в этот метод

2021-05-08 12:33 UTC, andrey-star approved these changes

2021-05-08 13:33 UTC, rorione requested changes
Все норм, но проверки существования в контроллере - странная вещь.
Порядок шагов в тестах, что я предложил в комментариях очень сильно облегчает читаемость кода, хотелось бы видеть все тесты +- такими

2021-05-08 13:33 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/article/section/controller/SectionController.kt
>          val section = service.getById(sectionId)
Проверка на существование версии излишняя. Нужно после получения секции сверить, что id версии совпадает с id версии в секции, которую получили.

2021-05-08 13:33 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/article/section/controller/SectionController.kt
> +        checkArticleVersionExists(versionId)
Проверка на существование версии должна быть в сервисе

2021-05-08 13:33 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/article/section/controller/SectionController.kt
> +        checkArticleVersionExists(versionId)
Проверка на существование версии не нужна, ошибка в таком случае должна бросаться из сервиса при checkAccess()

2021-05-08 13:33 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/article/section/controller/SectionController.kt
> +        checkArticleVersionExists(versionId)
Проверка на существование версии должна быть в сервисе

2021-05-08 13:33 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/article/section/controller/SectionController.kt
> +        checkArticleVersionExists(versionId)
Проверка на существование версии должна быть в сервисе

2021-05-08 13:33 UTC, rorione commented on backend/src/test/kotlin/com/jetbrains/life_science/section/controller/SectionControllerTest.kt
> +        val sections = getArticleVersionSections(1)
Лучше все-таки делать в такой последовательности:
1) Preparing expected data
2) Action
3) Check
(и можно даже прям подписывать эти шаги)

2021-05-08 13:33 UTC, rorione commented on backend/src/test/kotlin/com/jetbrains/life_science/section/controller/SectionControllerTest.kt
> +        val section = get(1, 3)
Лучше все-таки делать в такой последовательности:
1) Preparing expected data
2) Action
3) Check

(и можно даже прям подписывать эти шаги)

2021-05-08 13:33 UTC, rorione commented on backend/src/test/kotlin/com/jetbrains/life_science/section/controller/SectionControllerTest.kt
> +        val sectionDTO = SectionDTO(
Лучше все-таки делать в такой последовательности:
1) Preparing expected data
2) Action
3) Check

(и можно даже прям подписывать эти шаги)

2021-05-08 13:33 UTC, rorione commented on backend/src/test/kotlin/com/jetbrains/life_science/section/controller/SectionControllerTest.kt
> +        val parameters = listOf(
Лучше все-таки делать в такой последовательности:
1) Preparing expected data
2) Action
3) Check

(и можно даже прям подписывать эти шаги)

2021-05-08 13:33 UTC, rorione commented on backend/src/test/kotlin/com/jetbrains/life_science/section/controller/SectionControllerTest.kt
> +        val publishedArticleVersionId = 1L
Лучше все-таки делать в такой последовательности:
1) Preparing expected data
2) Action
3) Check

(и можно даже прям подписывать эти шаги)

2021-05-08 13:33 UTC, rorione commented on backend/src/test/kotlin/com/jetbrains/life_science/section/controller/SectionControllerTest.kt
> +        val publishedArticleVersionId = 1L
Лучше все-таки делать в такой последовательности:
1) Preparing expected data
2) Action
3) Check

(и можно даже прям подписывать эти шаги)

2021-05-09 08:16 UTC, Borodin239 commented on backend/src/test/kotlin/com/jetbrains/life_science/section/controller/SectionControllerTest.kt
> +        val sectionDTO = SectionDTO(
Здесь это просто физически невозможно, ибо ты не знаешь какой именно id будет присвоен при создании, поэтому создавать expectedSection надо после get запроса и проверки id на null

2021-05-09 08:35 UTC, Borodin239 commented on backend/src/main/kotlin/com/jetbrains/life_science/article/section/controller/SectionController.kt
>          val section = service.getById(sectionId)
Это не так, ибо если будет попытка сделать запрос по невалидному ArticleVersionID, то ты ожидаешь всё таки получить NotFoundException -- это логичнее

2021-05-09 08:37 UTC, Borodin239 commented on backend/src/main/kotlin/com/jetbrains/life_science/article/section/controller/SectionController.kt
> +        checkArticleVersionExists(versionId)
Проверка на существование осуществляется через сервис, просто было бы странно если бы ты делал запрос в сервис и каждый раз при проверке на существование articleVersion ловил исключение

2021-05-09 08:39 UTC, Borodin239 commented on backend/src/main/kotlin/com/jetbrains/life_science/article/section/controller/SectionController.kt
> +        checkArticleVersionExists(versionId)
Я, конечно, могу внести, но по-хорошему один метод выполняет одну задачу. CheckAccess() -- это про проверку прав доступа к секциям. А checkArticleVersionExists -- это про проверку на существование articleVersion

2021-05-09 08:39 UTC, Borodin239 commented on backend/src/main/kotlin/com/jetbrains/life_science/article/section/controller/SectionController.kt
> +        checkArticleVersionExists(versionId)
Тем более в остальных методах не избавиться от checkArticleVersionExists => просто внести метод целиком тоже не вариант

2021-05-09 08:40 UTC, Borodin239 commented on backend/src/main/kotlin/com/jetbrains/life_science/article/section/controller/SectionController.kt
> +        checkArticleVersionExists(versionId)
См выше

2021-05-09 08:40 UTC, Borodin239 commented on backend/src/main/kotlin/com/jetbrains/life_science/article/section/controller/SectionController.kt
> +        checkArticleVersionExists(versionId)
См выше

2021-05-09 08:42 UTC, Borodin239 commented on backend/src/test/kotlin/com/jetbrains/life_science/section/controller/SectionControllerTest.kt
> +        val section = get(1, 3)
Сделал это где было возможным, однако все тесты, которые мы писали на данный момент были такими: готовим данные для запроса, делаем запрос, проверяем. Это более чем ложится на твою концепцию, просто касаемо каждого конкретного запроса. А в некоторых местах сделать как ты просишь просто невозможно, ибо expectedDatа должна содержать результат предыдущего запроса

2021-05-09 08:42 UTC, Borodin239 commented on backend/src/test/kotlin/com/jetbrains/life_science/section/controller/SectionControllerTest.kt
> +        val publishedArticleVersionId = 1L
См выше

2021-05-09 08:43 UTC, Borodin239 commented on backend/src/test/kotlin/com/jetbrains/life_science/section/controller/SectionControllerTest.kt
> +        val sectionDTO = SectionDTO(
см выше

2021-05-09 08:43 UTC, Borodin239 commented on backend/src/test/kotlin/com/jetbrains/life_science/section/controller/SectionControllerTest.kt
> +        val publishedArticleVersionId = 1L
см выше

2021-05-09 10:35 UTC, avpotapov00 approved these changes

2021-05-09 21:12 UTC, rorione approved these changes

2021-05-09 21:13 UTC, merged