Review services
Life-Science-Project/LifeScience pull request #165
Opened 2021-05-07 13:31 UTC by avpotapov00

1) article version lifecycle part EDIT -> PENDING -> USER_PUBLISHED completed
2) user favourites made list of versions instead of articles
3) GET user-published versions method added

2021-05-07 13:55 UTC, rorione requested changes

2021-05-07 13:55 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/article/version/entity/ArticleVersion.kt
> +    val isArchived: Boolean get() = state == State.PUBLISHED || state == State.USER_PUBLISHED
Не работает

2021-05-07 13:55 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/article/review/controller/ReviewController.kt
> +    @PatchMapping("/{versionId}/request-review/global")
В контроллере уже есть {versionId} и непонятно зачем убирать /reviews/ из пути контроллера

2021-05-07 13:55 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/article/review/request/service/ReviewRequestServiceImpl.kt
> +        if (repository.existsByVersionIdAndResolutionIsNull(info.versionId)) {
А у нас все старые review удаляются?

2021-05-07 13:55 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/user/master/service/UserServiceImpl.kt
>      override fun addFavourite(user: User, articleId: Long): User {
переименовать в articleVersionId, чтобы потом не запутаться

2021-05-07 13:55 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/user/master/service/UserServiceImpl.kt
>      override fun removeFavourite(user: User, articleId: Long) {
переименовать в articleVersionId, чтобы потом не запутаться

2021-05-07 14:10 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/article/review/request/service/ReviewRequestServiceImpl.kt
> +        if (repository.existsByVersionIdAndResolutionIsNull(info.versionId)) {
Нет, тут мы ищем ревью без резолюции (поэтому ищем где она null)

2021-05-07 14:22 UTC, andrey-star requested changes

2021-05-07 14:22 UTC, andrey-star commented on frontend/build.gradle
> +}
?

2021-05-07 14:22 UTC, andrey-star commented on backend/src/test/resources/scripts/add_test_data.sql
> +       (2, 2);
\n

2021-05-07 14:22 UTC, andrey-star commented on backend/src/main/kotlin/com/jetbrains/life_science/util/EnumUtils.kt
> +inline fun <reified T : Enum<*>> enumValueOrNull(name: String): T? =
Tут лучше использовать стандартный valueOf и ловить IllegalArgument.
Nullable сам намекает, что OrNull
T должно быть наследником Enum<T>

2021-05-07 14:53 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/article/review/response/service/ReviewServiceImpl.kt
> +        }
создавать запрос на ревью у самого же себя? мне кажется админ может ни у кого не спрашивая просто поменять стейт, если что - по аудиту будет видно

2021-05-07 14:55 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/article/version/controller/ArticleVersionController.kt
> +    @PatchMapping("/{versionId}/to-edit")
хм, я думал когда хотим откатить свою же заявку и сделать снова редактируемым при удалении запроса на ревью, но кажется это можно сделать прямо там, поэтому это уберу

2021-05-07 15:15 UTC, andrey-star commented on backend/src/main/kotlin/com/jetbrains/life_science/article/review/response/service/ReviewServiceImpl.kt
> +        }
в плане нет else. Что будет, если там нулл?

2021-05-08 11:02 UTC, andrey-star approved these changes

2021-05-08 14:08 UTC, merged