elasticsearch data populator added
Life-Science-Project/LifeScience pull request #185
Opened 2021-05-13 17:37 UTC by avpotapov00

2021-05-13 18:55 UTC, andrey-star requested changes

2021-05-13 18:55 UTC, andrey-star commented on backend/build.gradle.kts
> +    implementation("com.google.code.gson:gson:2.8.5")
есть jackson

2021-05-13 18:55 UTC, andrey-star commented on backend/src/test/kotlin/com/jetbrains/life_science/util/populator/ElasticPopulator.kt
> +        return Gson().fromJson<List<Any>>(text, List::class.java)
jackson

2021-05-13 18:55 UTC, andrey-star commented on backend/src/test/kotlin/com/jetbrains/life_science/util/populator/ElasticPopulator.kt
> +    }
Зачем обертки над всеми функциями популятора? можно перенести prepareData в популятор и обернуть только ее

2021-05-14 07:48 UTC, andrey-star approved these changes

2021-05-14 08:32 UTC, rorione approved these changes

2021-05-14 08:38 UTC, merged