back/features/article and category dependencies
Life-Science-Project/LifeScience pull request #237
Opened 2021-07-03 14:01 UTC by Borodin239

2021-07-03 22:04 UTC, avpotapov00 requested changes
+ Я не нашел тестов, проверяющих, что после добавления такого Article, его можно найти как и из первой категории, так и из второй

2021-07-03 22:04 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/category/service/CategoryServiceImpl.kt
> +    override fun getCategories(ids: List<Long>): MutableList<Category> {
отсюда нужно возвращать List

2021-07-04 07:46 UTC, Borodin239 commented on backend/src/main/kotlin/com/jetbrains/life_science/article/primary/service/ArticleServiceImpl.kt
>      override fun updateById(info: ArticleInfo): Article {
Хороший вопрос

2021-07-04 08:01 UTC, rorione requested changes

2021-07-04 08:01 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/category/service/CategoryServiceImpl.kt
> +        return ids.map { getCategory(it) } as MutableList<Category>
Если возвращать List, то, по идее, не нужно будет даже юзать 'as MutableList<Category>'

2021-07-04 08:32 UTC, Borodin239 commented on backend/src/main/kotlin/com/jetbrains/life_science/article/primary/repository/ArticleRepository.kt
> +    fun findAllByCategories(category: Category): List<Article>
Потому что было изменено поле у сущности Article. Теперь это список и JPARepository не понимает что такое findAllByCategoryId. Однако ты прав, ни старый, ни новый метод из репозитория не использовались

2021-07-04 13:04 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/article/primary/repository/ArticleRepository.kt
> +    fun findAllByCategories(category: Category): List<Article>
findAllByCategoriesId будет работать, но, видимо, действительно стоит пока этот метод удалить

2021-07-06 07:45 UTC, closed without merging