Add authorization
Life-Science-Project/LifeScience pull request #24
Opened 2021-04-05 10:48 UTC by Borodin239

2021-04-05 12:49 UTC, rorione requested changes
Надо отформатировать, чтобы лайнер не ругался. Остальное в комментах.

2021-04-05 12:49 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/config/WebSecurityConfig.kt
> +    internal var userDetailsService: UserDetailsServiceImpl? = null
Точно ли нужны nullable поля? Да и Autowired через поле тоже не очень классно, насколько знаю. Где возможно, сделать через конструктор

2021-04-05 12:49 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/config/jwt/JWTAuthTokenFilter.kt
> +    private val tokenProvider: JWTProvider? = null
Аналогично nullable поля и Autowired не через конструктор

2021-04-05 12:49 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/config/jwt/JWTProvider.kt
> +    lateinit var userRepository: UserRepository
Autowired не через конструктор

2021-04-05 12:49 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/user/AuthController.kt
> +    lateinit var authenticationManager: AuthenticationManager
Autowired не через конструктор

2021-04-05 12:49 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/user/AuthController.kt
> +                user.roles!!.stream().map { role -> SimpleGrantedAuthority(role.name) }
Это не точно, но вроде в Kotlin можно без стрима это сделать точно так же)

2021-04-05 12:49 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/user/AuthController.kt
> +        if (!userCandidate.isPresent) {
Тут можно вынести копипасту с Return(..., BAD_REQUEST) и генерить ифами только строчку

2021-04-05 12:49 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/user/ResponseMessage.kt
> +class ResponseMessage(var message: String?)
Убрать nullable поле

2021-04-05 12:49 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/user/dto/LoginDTO.kt
> +    @NotBlank
Аннотации валидации в конструкторе должны начинаться с @field:<твоя аннотация>
Ex: @field:NotBlank

2021-04-05 12:49 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/user/dto/LoginDTOToInfoAdapter.kt
> +    override fun getFirstName(): String? {
Хотелось бы, чтобы все эти данные были not null, соответственно - сделать не nullable поля

2021-04-05 12:49 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/user/dto/NewUserDTO.kt
> +    @NotBlank
Аналогично изменить на @field:<field_name>

2021-04-05 12:49 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/user/entity/Role.kt
> +    @GeneratedValue(strategy = GenerationType.AUTO)
Читал, что лучше ставить strategy = GenerationType.IDENTITY
=)

2021-04-05 12:49 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/user/entity/User.kt
> +    var firstName: String? = null,
Сделать поля не nullable

2021-04-05 12:49 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/user/repository/UserRepository.kt
> +    fun deleteByUsername(username: String)
А уникальные ли у нас username в бд? Есть, конечно, проверка при регистрации, но хотелось бы, чтобы об этом знала сама база. Лучше, наверное, сделать удаление по Id.

2021-04-05 12:49 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/user/service/UserDetailsServiceImpl.kt
> +    lateinit var userRepository: UserRepository
Сделать autowired через конструктор

2021-04-05 12:49 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/user/service/UserDetailsServiceImpl.kt
> +            user.roles!!.stream().map { role -> SimpleGrantedAuthority(role.name) }
Map в Kotlin можно юзать прям к списку, не используя стримы

2021-04-05 12:49 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/user/service/UserServiceImpl.kt
> +        val user = userFactory.createUser(userInfo, mutableListOf(roleRepository.findByName("ROLE_USER")))
Полагаю, можно immutable list

2021-04-05 17:42 UTC, andrey-star requested changes
Поправить кодстайл, чтобы линтер проходился.
Сделать TODO на добавление refreshToken, чтобы не приходилось логиниться каждые 86400 секунд

2021-04-05 17:42 UTC, andrey-star commented on src/main/kotlin/com/jetbrains/life_science/exceptions/UserAlreadyExistException.kt
> +    }
Думаю, primary конструктора от message достаточно

2021-04-05 17:42 UTC, andrey-star commented on src/main/kotlin/com/jetbrains/life_science/user/AuthController.kt
> +    lateinit var roleRepository: RoleRepository
Не используется

2021-04-05 17:42 UTC, andrey-star commented on src/main/kotlin/com/jetbrains/life_science/user/AuthController.kt
> +            )
Кидать `UserNotFoundException`

2021-04-05 17:42 UTC, andrey-star commented on src/main/kotlin/com/jetbrains/life_science/user/AuthController.kt
> +        if (!userCandidate.isPresent) {
+ все равно будем делать ошибки через ControllerAdvice, так что можно кидать здесь соответствующий Exception

2021-04-05 17:42 UTC, andrey-star commented on src/main/kotlin/com/jetbrains/life_science/user/AuthController.kt
> +                return ResponseEntity(
`UserAlreadyExistsException`

2021-04-05 17:42 UTC, andrey-star commented on src/main/kotlin/com/jetbrains/life_science/user/ResponseMessage.kt
> +class ResponseMessage(var message: String?)
Или удалить весь класс, потому что в основном используется для обработки ошибок, которые на себя возьмет ControllerAdvice.

2021-04-05 17:42 UTC, andrey-star commented on src/main/kotlin/com/jetbrains/life_science/user/entity/Role.kt
> +class Role(
Мне кажется, Role должен реализовывать GrantedAuthority, не уверен

2021-04-05 17:42 UTC, andrey-star commented on src/main/kotlin/com/jetbrains/life_science/user/AuthController.kt
> +                user.roles!!.stream().map { role -> SimpleGrantedAuthority(role.name) }
Мне кажется, Role должен реализовывать GrantedAuthorityб тогда не придется мапить

2021-04-05 17:42 UTC, andrey-star commented on src/main/kotlin/com/jetbrains/life_science/user/entity/Role.kt
> +
Если `User` связан через `@ManyToMany` с `Role`, не должен ли Role содержать список юзеров?
Кажется, работает схема
```
User:
@ManyToMany(fetch = FetchType.EAGER)
roles: Set<Role>

Role:
@Transient
@ManyToMany(mappedBy = "roles")
users: Set<User>
```

2021-04-05 17:42 UTC, andrey-star commented on src/main/kotlin/com/jetbrains/life_science/user/entity/User.kt
> +    var roles: MutableCollection<Role>? = null
См. комvентарий к `Role.kt`

2021-04-05 17:42 UTC, andrey-star commented on src/main/kotlin/com/jetbrains/life_science/user/service/UserDetailsServiceImpl.kt
> +            ?: throw UsernameNotFoundException("User '$username' not found")
Exception никогда не кидается. Заменить на `orElseThrow`

2021-04-05 17:42 UTC, andrey-star commented on src/main/resources/application.properties
> +assm.app.jwtSecret=jwtAssmSecretKey
Добавить TODO, чтобы поместить ключ в переменные среды

2021-04-06 10:03 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/user/AuthController.kt
> +                user.roles!!.stream().map { role -> SimpleGrantedAuthority(role.name) }
Да, вызов стрима не обязателен. Если убрать вызов этой функции, то будет обычная операция над коллекцией, при этом на каждый такой цепочный вызов будет создаваться промежуточная.
В котлине потоковая обработка бывает двух видов:
* ленивая, запускается только когда есть терминальная операция в конце, аналог стримов, называется Sequence (метод коллекции asSequence())
* не ленивая - выполняется сразу при вызове, на каждый шаг создается промежуточная коллекция

Не ленивый метод показывает себя лучше на маленьких данных, поскольку накладные расходы на обеспечение ленивого потока иногда больше, чем на перекопирование. Поэтому на небольших данных лучше использовать не ленивый метод, то есть в данном примере сделать user.roles.map { role -> SimpleGrantedAuthority(role.name) }

2021-04-06 10:06 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/user/entity/Role.kt
> +
@andrey-star А зачем нам уметь получать через сущность роли список пользователей с такой ролью? Пока что мне кажется добавление этого поля будет просто лишняя нагрузка на хибер.

2021-04-06 10:08 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/config/WebSecurityConfig.kt
> +    }
@andrey-star да

2021-04-06 10:09 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/user/service/UserServiceImpl.kt
> +        val user = userFactory.createUser(userInfo, mutableListOf(roleRepository.findByName("ROLE_USER")))
@rorione насколько я помню там хибер ныть начнет, что не может так сделать тк он под капотом сам добавляет туда, + хотелось бы уметь добавлять роли просто добавляя в список

2021-04-06 10:09 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/user/service/UserDetailsServiceImpl.kt
> +            user.roles!!.stream().map { role -> SimpleGrantedAuthority(role.name) }
@Borodin239 см мой длиннопост выше

2021-04-06 10:14 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/user/AuthController.kt
> +                user.roles!!.stream().map { role -> SimpleGrantedAuthority(role.name) }
Да, это правда
В котлине есть аналог стримов, называется Sequence. 
Есть два вида потоковой обработки:
* Ленивая - ведет себя аналогично стриму, хорошо показывает себя на больших данных, тк промежуточные коллекции для хранения состояния между операциями не создаются. Получаются из коллекции: list.asSequence().map {...}
* Не ленивая - используется как list.map{ ... } - то же самое, как с Sequence, только без asSequence(). Отличается тем, что запускается сразу, не дожидаясь терминальной операции, и для всех промежуточных состояний создает промежуточную коллекцию -> перекопирования. Показывает хорошо себя там, где накладные расходы на лень выше расходов на перекопирование, то есть на небольших данных

Поэтому в этом случае следует применить не ленивую обработку и написать user.roles.map { role -> ...

2021-04-06 11:26 UTC, andrey-star commented on src/main/kotlin/com/jetbrains/life_science/user/entity/Role.kt
> +
В таблице ролей не будет юзеров из-за Transient, просто на уровне аннотаций проще

2021-04-07 08:09 UTC, avpotapov00 reviewed
Учти замечания ребят, я с ними согласен

2021-04-07 19:50 UTC, Borodin239 commented on src/main/kotlin/com/jetbrains/life_science/user/ResponseMessage.kt
> +class ResponseMessage(var message: String?)
Пока я оставлю для вывода сообщения об успешной регистрации, там где выводились сообщения об ошибках я убрал обращение к ResponseMessage и заменил пробрасыванием нужных исключений. Nullable поле убрал.

2021-04-07 20:27 UTC, Borodin239 commented on src/main/kotlin/com/jetbrains/life_science/user/repository/UserRepository.kt
> +    fun deleteByUsername(username: String)
Да, username уникальный, я для этого добавил пометку unique=true, поэтому проблем не должно возникнуть, ибо уникальность дополнительно гарантируется на уровне БД

2021-04-07 20:50 UTC, Borodin239 commented on src/main/kotlin/com/jetbrains/life_science/user/service/UserServiceImpl.kt
> +        val user = userFactory.createUser(userInfo, mutableListOf(roleRepository.findByName("ROLE_USER")))
@rorione Саня прав, хибер ныть действительно начинает.

2021-04-07 21:16 UTC, Borodin239 commented on src/main/kotlin/com/jetbrains/life_science/user/AuthController.kt
> +    lateinit var roleRepository: RoleRepository
Он мне понадобится в следующей issue. Поэтому оставлю

2021-04-07 21:25 UTC, Borodin239 commented on src/main/resources/application.properties
> +assm.app.jwtSecret=jwtAssmSecretKey
Добавил в issue

2021-04-07 21:26 UTC, Borodin239 commented on src/main/kotlin/com/jetbrains/life_science/config/jwt/JWTAuthTokenFilter.kt
> +                val userDetails = userDetailsService!!.loadUserByUsername(username)
Хорошо, я сделаю после того как смёрджим с мастером, чтобы не стопорить процесс

2021-04-07 21:39 UTC, Borodin239 commented on src/main/kotlin/com/jetbrains/life_science/user/entity/Role.kt
> +class Role(
Добавил в Issue -- подумаю на эту тему на днях.

2021-04-08 12:36 UTC, avpotapov00 approved these changes

2021-04-08 18:22 UTC, andrey-star approved these changes

2021-04-08 18:34 UTC, rorione approved these changes

2021-04-08 18:35 UTC, merged