Features/draft services #LS-36 #LS-37
Life-Science-Project/LifeScience pull request #251
Opened 2021-07-09 19:41 UTC by Borodin239

2021-07-11 22:35 UTC, avpotapov00 requested changes
Так как методы сервисов имеют side-эффекты в виде записи в бд, в тестах нужно также проверять корректно ли записались в бд данные, соответственно недостаточно просто проверять возвращаемый объект из метода.
Нужно убеждаться в этом каким-то из доступных способов, например получением этого объекта еще раз, через get.
Стоит также помнить, что тестовые методы помечены как Transactional, а это значит, что хибер может сразу не слить все изменения в бд. То есть если добавить ребенка родителю в many-to-many отношении, то родитель до завершения транзакции не будет видеть ребенка, тк изменения еще не слиты завершением транзакции. Это некоторый недостаток Transactional тестов, но его можно обойти, используя enityManager.flush() метод, который заставит слить изменения в бд.

2021-07-11 22:35 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/approach/service/DraftApproachServiceImpl.kt
> +        get(id)
заменить на вызов exists репозитория с проверкой на наличие, тут незачем всю сущность тащить

2021-07-11 22:35 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/protocol/service/DraftProtocolServiceImpl.kt
> +        get(draftProtocolId)
Заменить на вызов метода exists у репозитория - незачем тащить всю сущность

2021-07-11 22:35 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/protocol/service/DraftProtocolServiceImpl.kt
> +    override fun update(protocolInfo: DraftProtocolInfo): DraftProtocol {
Здесь не произойдет сохранения изменения в сущности, так как в репозиторий вы не сохраняете, а метод как @Transactional не помечен.
В тестах на этот метод вы проверяете что сущность вернется из этого метода обновленная, так и происходит, однако вы нигде не проверяете, что она в таком обновленном виде сохранилась.
Поэтому в тестах на метод, который ходит в базу с изменениями, нужно также проверять что эти изменения видны.

2021-07-11 22:35 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/approach/service/DraftApproachServiceImpl.kt
> +    override fun update(info: DraftApproachInfo): DraftApproach {
Здесь не произойдет сохранения изменения в сущности, так как в репозиторий вы не сохраняете, а метод как @Transactional не помечен.
В тестах на этот метод вы проверяете что сущность вернется из этого метода обновленная, так и происходит, однако вы нигде не проверяете, что она в таком обновленном виде сохранилась.
Поэтому в тестах на метод, который ходит в базу с изменениями, нужно также проверять что эти изменения видны.

2021-07-11 22:35 UTC, avpotapov00 commented on backend/src/test/kotlin/com/jetbrains/life_science/protocol/draft/service/DraftProtocolServiceTest.kt
> +        val approach = PublicApproach(
Вынести в отдельную функцию, чтобы каждый раз не писать mutableListOf()

2021-07-11 22:35 UTC, avpotapov00 commented on backend/src/test/kotlin/com/jetbrains/life_science/protocol/draft/service/DraftProtocolServiceTest.kt
> +        val approach = PublicApproach(
Вынести в отдельную функцию, чтобы каждый раз не писать mutableListOf()

2021-07-11 22:35 UTC, avpotapov00 commented on backend/src/test/kotlin/com/jetbrains/life_science/protocol/draft/service/DraftProtocolServiceTest.kt
> +        val approach = PublicApproach(
Вынести в отдельную функцию, чтобы каждый раз не писать mutableListOf()

2021-07-11 22:35 UTC, avpotapov00 commented on backend/src/test/kotlin/com/jetbrains/life_science/protocol/draft/service/DraftProtocolServiceTest.kt
> +        assertTrue(draftProtocol.participants.any { it.id == expectedOwnerId })
вынести в assertHaveParticipant

2021-07-11 22:35 UTC, avpotapov00 commented on backend/src/test/kotlin/com/jetbrains/life_science/approach/draft/service/DraftApproachServiceTest.kt
> +        assertTrue(draftApproach.participants.any { it.id == owner.id })
вынести в assertHaveParticipant

2021-07-11 22:35 UTC, avpotapov00 commented on backend/src/test/kotlin/com/jetbrains/life_science/approach/draft/service/DraftApproachServiceTest.kt
> +        assertTrue(draftApproach.categories.any { it.id == category.id })
вынести в assertHaveCategory

2021-07-12 05:18 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/protocol/service/DraftProtocolServiceImpl.kt
> +    override fun update(protocolInfo: DraftProtocolInfo): DraftProtocol {
Разве return repository.save(protocol) не сделает свое дело?

2021-07-12 05:21 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/protocol/service/DraftProtocolServiceImpl.kt
> +    override fun update(protocolInfo: DraftProtocolInfo): DraftProtocol {
Да и в тестахсоздается инфо с новыми данными (как минимум обновленным именем), а совпадение имени проверяется. Согласен, что надо делать get() в тестах, но тут обновление должно работать

2021-07-12 07:20 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/protocol/service/DraftProtocolServiceImpl.kt
> +    override fun update(protocolInfo: DraftProtocolInfo): DraftProtocol {
Да, сори, это относится только в DraftApproachService. Я сюда продублировал тк оч похоже, но что тут все делается - не заметил.

2021-07-12 18:53 UTC, avpotapov00 approved these changes

2021-07-12 18:53 UTC, merged