Refactoring/tests #LS-68
Life-Science-Project/LifeScience pull request #267
Opened 2021-07-15 12:22 UTC by Borodin239

2021-07-15 12:57 UTC, rorione requested changes

2021-07-15 12:57 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/approach/entity/PublicApproach.kt
> +        strategy = GenerationType.IDENTITY,
Почему где-то IDENTITY, а где-то SEQUENCE?

2021-07-15 14:49 UTC, Borodin239 commented on backend/src/main/kotlin/com/jetbrains/life_science/approach/entity/PublicApproach.kt
> +        strategy = GenerationType.IDENTITY,
Поправил

2021-07-16 00:53 UTC, avpotapov00 approved these changes

2021-07-16 00:53 UTC, merged