Features/publish protocol review request service #LS-77
Life-Science-Project/LifeScience pull request #274
Opened 2021-07-16 12:48 UTC by Borodin239

2021-07-16 13:31 UTC, rorione requested changes

2021-07-16 13:31 UTC, rorione commented on src/test/kotlin/com/jetbrains/life_science/review/request/service/maker/PublishProtocolRequestMaker.kt
> +fun makePublishProtocolRequest(
makePublishProtocolRequest**Info**

2021-07-16 20:33 UTC, rorione approved these changes

2021-07-18 21:21 UTC, avpotapov00 approved these changes

2021-07-18 21:21 UTC, merged