Features/edit record #LS-87
Life-Science-Project/LifeScience pull request #279
Opened 2021-07-19 18:00 UTC by Borodin239

2021-07-20 06:40 UTC, rorione requested changes

2021-07-20 06:40 UTC, rorione commented on src/test/kotlin/com/jetbrains/life_science/edit_record/approach/service/ApproachEditRecordServiceTest.kt
> +}
добавить тест на удаление секции, которой нет ни в аппроаче, ни в рекорде,
добавить тест на удаление секции, которая только в рекорде,
добавить тесты на повторное удаление\добавление секций

2021-07-20 06:43 UTC, rorione requested changes

2021-07-20 06:43 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/edit_record/entity/ApproachEditRecord.kt
> -    var request: ApproachReviewRequest?
почему у нас теперь нет связи editRecord и запроса на ревью?

2021-07-20 12:05 UTC, Borodin239 commented on src/main/kotlin/com/jetbrains/life_science/edit_record/entity/ApproachEditRecord.kt
> -    var request: ApproachReviewRequest?
Она сохранилась, только в самом реквесте, а в обратную сторону практического применения этого поля я не вижу.

2021-07-20 14:20 UTC, Borodin239 commented on src/test/kotlin/com/jetbrains/life_science/edit_record/approach/service/ApproachEditRecordServiceTest.kt
> +}
В тесте на повторное добавление не добавлял, так как договорились игнорировать такие запросы к сервису на добавление и просто ничего не изменится (например, как в обычном approach). Новые тесты добавил.

2021-07-20 15:31 UTC, rorione requested changes

2021-07-20 15:31 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/edit_record/service/ApproachEditRecordService.kt
> +    fun recoverDeletedSection(id: Long, section: Section): ApproachEditRecord
а как мы поймем, какой метод нам вызывать, удалить существующую, или ту, которая в рекорде? мне кажется это проверять должен именно этот сервис( deleteSection -> deleteExisting\deleteCreatedSection)

2021-07-20 15:31 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/edit_record/service/ApproachEditRecordService.kt
> +    fun recoverDeletedSection(id: Long, section: Section): ApproachEditRecord
аналогично с добавлением

2021-07-21 10:01 UTC, avpotapov00 requested changes

2021-07-21 14:07 UTC, Borodin239 commented
После всех обсуждений написал финальная версия функционала сервиса, теперь для работы с секциями остались только методы addSection и deleteSection. 

_Поведение addSection:_ 
1. Смотрит есть ли секция в deletedSections, если есть -- удаляет её из deleted и заканчивает работу. 
2. Если нет в deletedSections, то он идёт в approach или createdSections, если секция есть там, то прокидывает исключение SectionAlreadyExists.
3. Если секции там нет, то добавляет её в createdSections.

_Поведение deleteSection:_ 
1. Проверяет наличие секции в deletedSection и прокидывает SectionAlreadyExistsException, если она там есть.
2. Если в deletedSection её не было и она есть в approach, то секция добавляется в deletedSection.
3. Если секция есть в createdSections, то она удаляется из deletedSections.
4. В противном случае прокидывается SectionNotFoundException.

2021-07-22 06:29 UTC, avpotapov00 requested changes

2021-07-22 06:29 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/util/OtherConstants.kt
> +val UTC = ZoneId.of("UTC")
UTCZone

2021-07-22 08:29 UTC, Borodin239 commented on src/main/kotlin/com/jetbrains/life_science/edit_record/service/ApproachEditRecordServiceImpl.kt
> +            throw SectionAlreadyExistsException("Section with id ${section.id} is already exists in deletedSections")
Да, SectionAlreadyDeletedException будет лучше. Когда писал подумал что фактический мы так или иначе добавляем секцию в EditRecord, но ты прав.

2021-07-22 08:29 UTC, Borodin239 commented on src/main/kotlin/com/jetbrains/life_science/edit_record/service/ApproachEditRecordServiceImpl.kt
> +        if (section in approachEditRecord.deletedSections) {
Поправил

2021-07-22 08:34 UTC, rorione approved these changes

2021-07-22 10:51 UTC, merged