Bugs/approach&protocol mapping #LS-120
Life-Science-Project/LifeScience pull request #323
Opened 2021-08-02 11:13 UTC by Borodin239

2021-08-02 11:17 UTC, rorione approved these changes

2021-08-02 13:17 UTC, avpotapov00 requested changes

2021-08-02 13:17 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/container/approach/service/PublicApproachServiceImpl.kt
> +    override fun hasProtocol(approachId: Long, protocol: PublicProtocol): Boolean {
Метод не используется

2021-08-02 13:17 UTC, rorione requested changes

2021-08-02 13:17 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/container/approach/service/PublicApproachService.kt
> +    fun hasProtocol(approachId: Long, protocol: PublicProtocol): Boolean
А зачем он?

2021-08-02 14:28 UTC, Borodin239 commented on src/main/kotlin/com/jetbrains/life_science/container/approach/service/PublicApproachService.kt
> +    fun hasProtocol(approachId: Long, protocol: PublicProtocol): Boolean
Хороший вопрос

2021-08-03 09:32 UTC, rorione requested changes

2021-08-03 09:32 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/container/approach/repository/PublicApproachRepository.kt
> +    fun existsByIdAndProtocolsContains(approachId: Long, protocol: PublicProtocol): Boolean
Где используется этот метод?

2021-08-03 12:07 UTC, Borodin239 commented on src/main/kotlin/com/jetbrains/life_science/container/approach/repository/PublicApproachRepository.kt
> +    fun existsByIdAndProtocolsContains(approachId: Long, protocol: PublicProtocol): Boolean
Нигде, я решил его не убирать, так как он показался потенциально нужным. С другой стороны ты прав, если понадобится -- напишем

2021-08-03 12:10 UTC, rorione approved these changes

2021-08-04 11:31 UTC, avpotapov00 approved these changes

2021-08-04 11:31 UTC, merged