Feature/replicator
Life-Science-Project/LifeScience pull request #324
Opened 2021-08-03 12:51 UTC by avpotapov00

2021-08-03 13:13 UTC, rorione requested changes

2021-08-03 13:13 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/replicator/deserializer/category/CategoryReplicator.kt
> +    fun createOne(storageEntity: CategoryStorageEntity) {
сделать приватным

2021-08-03 13:13 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/replicator/deserializer/category/CategoryReplicator.kt
> +            parents = storageEntity.parents.map { categoryRepository.findCategoryById(it)!! }.toMutableList(),
лучше убрать "!!" и бросить нормальное исключение через Optional

2021-08-03 13:13 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/replicator/deserializer/content/ContentReplicator.kt
> +    @Transactional
Транзакций в эластике нет(

2021-08-03 13:13 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/replicator/serializer/section/SectionToStorageEntityMapper.kt
> +            hidden = !section.visible,
меня что-то сильно пугает то, что у нас и hidden и visible есть, надо бы отрефакторить

2021-08-04 08:49 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/replicator/deserializer/category/CategoryReplicator.kt
> +            parents = storageEntity.parents.map { categoryRepository.findCategoryById(it)!! }.toMutableList(),
getOne или свой метод в этом классе лучше, так придется вносить изменения в код в основном модуле для тестового модуля, что делать нельзя

2021-08-04 16:51 UTC, rorione approved these changes

2021-08-05 08:18 UTC, merged