Ошибка в поиске #LS-126
Life-Science-Project/LifeScience pull request #336
Opened 2021-08-06 18:12 UTC by Borodin239

2021-08-08 06:22 UTC, rorione requested changes

2021-08-08 06:22 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/search/service/SearchServiceImpl.kt
> +        val queryBuilder = QueryBuilders.prefixQuery("names", query.text.toLowerCase())
я же попросил убрать и там, и там и вставить в одном месте - в адаптере

2021-08-08 06:28 UTC, rorione requested changes

2021-08-08 06:28 UTC, rorione commented on src/test/kotlin/com/jetbrains/life_science/search/service/SearchServiceTest.kt
> +        val searchResultMix = service.search(searchQueryInfoMixedCase)
Надо было сделать отдельный тест на mixedCase в suggest, а не в search

2021-08-09 08:20 UTC, Borodin239 commented on src/main/kotlin/com/jetbrains/life_science/search/service/SearchServiceImpl.kt
> +        val queryBuilder = QueryBuilders.prefixQuery("names", query.text.toLowerCase())
Я сделал, но потом мы с Сашей решили что надо это делать в сервисе, ибо адаптер должен реорганизовывать данные, но не изменять. Это с точки зрения архитектуры неверно.

2021-08-09 08:28 UTC, Borodin239 commented on src/test/kotlin/com/jetbrains/life_science/search/service/SearchServiceTest.kt
> +        val searchResultMix = service.search(searchQueryInfoMixedCase)
В отдельный тест решил не выносить, а расширить уже существующий. Иначе по сути копипаста будет

2021-08-09 08:29 UTC, rorione approved these changes

2021-08-09 08:36 UTC, merged