Entity structure and search implemented
Life-Science-Project/LifeScience pull request #35
Opened 2021-04-06 08:58 UTC by avpotapov00

2021-04-06 11:11 UTC, rorione requested changes

2021-04-06 11:11 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/search/controller/SearchController.kt
> +    fun search(@RequestBody queryDTO: SearchDTO): List<SearchResult> {
Нет проверки валидации дто

2021-04-06 11:11 UTC, rorione commented on src/main/kotlin/com/jetbrains/life_science/search/dto/SearchDTO.kt
> +    val query: String,
Нужно ли нам что-то делать, если дали пустой или бесконечно большой запрос? Я бы просто выдал ошибку валидации

2021-04-06 11:14 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/article/dto/ArticleCreationDTOToInfoAdapter.kt
> +    override val id: Long?
@rorione С @Documented это не работает, сущность не хиберовская

2021-04-06 11:15 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/container/entity/Container.kt
> +    var description: String?,
Ок, согласен

2021-04-06 18:10 UTC, andrey-star requested changes
Сложная структура удаления, было бы круто, если в описании пул реквеста прояснишь немного.

i18n лучше отдельным пул реквестом

2021-04-06 18:10 UTC, andrey-star commented on src/test/kotlin/com/jetbrains/life_science/method/service/MethodServiceImplTest.kt
> +import com.jetbrains.life_science.article.entity.Article // ktlint-disable
ktlint-disable не должен быть нужен

2021-04-07 06:42 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/container/entity/Container.kt
> +    @OnDelete(action = OnDeleteAction.NO_ACTION)
@andrey-star Чтобы не попытаться удалить метод при попытке удалить контейнер

2021-04-07 06:43 UTC, avpotapov00 commented on build.gradle.kts
> +compileKotlin.kotlinOptions.useIR = true
JB попросило поставить новый компилятор для бэкенда, который типа эффективнее

2021-04-07 06:55 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/search/dto/SearchDTO.kt
> +    val query: String,
@rorione нужно, но модификации поиска пойдут отдельной веткой, здесь прототип, чтобы в архитектуру легло я сделал

2021-04-07 07:04 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/method/service/MethodServiceImpl.kt
> +        val method = getMethod(id)
Справедливо)

2021-04-07 07:05 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/method/entity/Method.kt
> +    var containers: MutableList<Container> = mutableListOf()
да, котлин

2021-04-07 07:06 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/config/MessagesConfig.kt
> +class MessagesConfig {
Тут мы настраиваем бин MessageSourceAccessor, который более удобный в использовании, чем MessageSource. Здесь потом можно будет задавать нужную локаль ему, и она во всех местах станет такой, где у нас i18n

2021-04-07 07:07 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/article/repository/ArticleRepositoryImpl.kt
> +    override fun updateText(id: String, text: String) {
да, чтобы не тягать в память старый текст: он нам для обновления не нужен

2021-04-07 07:19 UTC, avpotapov00 commented on src/main/kotlin/com/jetbrains/life_science/search/units/SearchResult.kt
> +    val typeName: String,
Тогда по поиску правки отдельной веткой, тут есть что обсудить, это прост прототип поиска, чтобы понять что оно в принципе может взлететь

2021-04-07 08:03 UTC, rorione approved these changes

2021-04-07 08:42 UTC, andrey-star approved these changes
Nice

2021-04-07 08:44 UTC, merged