Update implementation
Life-Science-Project/LifeScience pull request #64
Opened 2021-04-16 22:01 UTC by rorione

2021-04-17 10:15 UTC, avpotapov00 requested changes

2021-04-17 10:15 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/article/version/service/ArticleVersionServiceImpl.kt
> +        searchService.update(version)
Сущности в эластике не должны здесь обновляться, тк их тут просто нет, тк это версия. Они обновляются только при апруве новой версии через удаление старых и создании новых. В противном случае мы получим исключение при попытке обновить неапрувнутую версию - будет не найден SearchUnit

2021-04-17 13:11 UTC, andrey-star requested changes
Добавить в Info поле id опциональным параметром, по умолчанию null

2021-04-17 13:11 UTC, andrey-star commented on backend/src/main/kotlin/com/jetbrains/life_science/article/master/service/ArticleServiceImpl.kt
> +        return repository.findById(id).get()
Здесь findById, но в SectionService getOne, так и задумано?

2021-04-18 07:42 UTC, andrey-star approved these changes
В ArticleService поменять название `updateById`-> `update`

2021-04-18 07:42 UTC, andrey-star commented on backend/src/main/kotlin/com/jetbrains/life_science/article/master/service/ArticleService.kt
> +    fun updateById(info: ArticleInfo): Article
Теперь просто update, не ById

2021-04-18 07:59 UTC, avpotapov00 approved these changes

2021-04-18 07:59 UTC, merged