user details added
Life-Science-Project/LifeScience pull request #65
Opened 2021-04-17 06:01 UTC by avpotapov00

2021-04-17 13:22 UTC, andrey-star requested changes
В существующих энтити заменить поле юзера с UserCredentials на User

2021-04-17 13:22 UTC, andrey-star commented on backend/src/main/kotlin/com/jetbrains/life_science/article/review/entity/Review.kt
> +    var reviewer: UserCredentials
Здесь не User?

2021-04-17 13:22 UTC, andrey-star commented on backend/src/main/kotlin/com/jetbrains/life_science/article/version/entity/ArticleVersion.kt
> +    val author: UserCredentials,
Не User?

2021-04-17 13:22 UTC, andrey-star commented on backend/src/main/kotlin/com/jetbrains/life_science/user/credentials/entity/LoginInfo.kt
> +interface LoginInfo {
поля вместо методов

2021-04-17 13:22 UTC, andrey-star commented on backend/src/main/kotlin/com/jetbrains/life_science/user/credentials/entity/UserInfo.kt
>  interface UserInfo {
поля вместо методов

2021-04-17 17:40 UTC, rorione requested changes

2021-04-17 17:40 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/user/credentials/service/UserCredentialsServiceImpl.kt
> +    fun checkUserNotExistsByEmail(email: String) {
checkUserNotExistsByEmail -> checkUserAlreadyExistsByEmail

2021-04-17 17:40 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/user/details/entity/User.kt
> +    val doctorDegree: DoctorDegree? = null,
Зачем nullable, если есть NONE?

2021-04-17 17:40 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/user/details/entity/User.kt
> +    val academicDegree: AcademicDegree? = null,
Тут бы тоже хорошо добавить состояние NONE

2021-04-18 08:07 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/user/credentials/service/UserCredentialsServiceImpl.kt
> +    fun checkUserNotExistsByEmail(email: String) {
Не очень понял тебя, а зачем тут такое, эта функция будет исключение бросать, а ты предлагаешь ее проинвертировать, но я же вызов ее не могу проинвертировать

2021-04-18 08:12 UTC, andrey-star commented on backend/src/main/kotlin/com/jetbrains/life_science/user/credentials/service/UserCredentialsServiceImpl.kt
> +    fun checkUserNotExistsByEmail(email: String) {
Мне кажется такой метод в целом не очень, потому что conditional логика, но в неявном виде. orElseThrow лучше выглядит, чтобы не повторять exception сделать метод, который не кидает, а возвращает exception

2021-04-18 08:16 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/user/credentials/service/UserCredentialsServiceImpl.kt
> +    fun checkUserNotExistsByEmail(email: String) {
@andrey-star у нас такие методы во всем коде уже есть, которые по названию говорят что они делают. Сейчас тогда просто внесу в основной метод условие, а потом обсудим

2021-04-18 08:18 UTC, andrey-star approved these changes

2021-04-18 10:15 UTC, rorione approved these changes

2021-04-19 15:23 UTC, merged