Modify registration
Life-Science-Project/LifeScience pull request #81
Opened 2021-04-20 15:27 UTC by Borodin239

Добавлены запросы на добавление информации в профиль и её редактирования и запрос на получение информации о пользователе

2021-04-20 15:30 UTC, avpotapov00 requested changes

2021-04-20 15:30 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/user/details/controller/UserController.kt
> +    @PostMapping("/add_details")
/update

2021-04-20 15:30 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/user/details/controller/UserController.kt
> +@RequestMapping("/user")
/api/user

2021-04-20 15:30 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/user/details/service/UserServiceImpl.kt
> +        return userRepository.save(userFactory.setParams(user, info))
Пометить метод как @Transactional и убрать repository.save(...)

2021-04-20 15:30 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/user/details/view/UserViewMapper.kt
> +        return UserView(
Сделать именованные параметры
id = user.id и тд

2021-04-20 15:53 UTC, rorione requested changes

2021-04-20 15:53 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/user/details/controller/UserController.kt
> +        @RequestBody addDetailsDTO: AddDetailsDTO,
@Validated

2021-04-20 15:53 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/user/details/dto/AddDetailsDTOToInfoAdapter.kt
> +class AddDetailsDTOToInfoAdapter(
Мне кажется, что можно хранить user внутри info, как это сделано в ArticleVersion

2021-04-20 19:06 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/user/details/controller/UserController.kt
> +    @DeleteMapping("")
("") не нужны

2021-04-20 19:08 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/user/details/service/UserServiceImpl.kt
> +        return userFactory.setParams(user, info)
Сделать проверку роли

2021-04-20 19:13 UTC, andrey-star requested changes

2021-04-20 19:13 UTC, andrey-star commented on backend/src/main/kotlin/com/jetbrains/life_science/user/details/controller/UserController.kt
> +    fun deleteProfile(
Тоже не по канону иметь отдельный delete c Principal. Можно добавить Principal в deleteUser и чекать, что юзер админ, либо удаляет свой профиль (у @rorione где-то было)

2021-04-21 10:00 UTC, rorione requested changes

2021-04-21 10:00 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/user/details/controller/UserController.kt
> +            userCredentialsService.delete(userId)
Несколько делитов в контроллере это плохо. Нужно, чтобы это делал сервис, причем @Transactional

2021-04-21 10:00 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/user/details/controller/UserController.kt
> +    private fun checkAccess(user: User, principal: Principal): Boolean {
Я не уверен, что проверки мы делаем в контроллере. Надо посоветоваться с Сашей и, если да, то остальные тоже перенести в контроллеры.

2021-04-21 10:00 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/user/details/controller/UserController.kt
> +        val user = userCredentialsService.getById(userId).user
Ты чтобы обновить user достаешь его прямо в контроллере? Полагаю, это ответственность сервиса.

2021-04-21 10:00 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/user/details/controller/UserController.kt
> +            userService.update(AddDetailsDTOToInfoAdapter(addDetailsDTO, user))
Соответственно, инфошке нужно засовывать user id

2021-04-21 21:05 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/user/details/controller/UserController.kt
> +    private fun checkAccess(user: User, principal: Principal): Boolean {
Да, я считаю, что в контроллере, как во "входной точке" они уместнее

2021-04-21 22:39 UTC, avpotapov00 approved these changes

2021-04-21 22:43 UTC, rorione approved these changes

2021-04-22 06:28 UTC, andrey-star approved these changes

2021-04-22 06:30 UTC, merged