Content version separate index
Life-Science-Project/LifeScience pull request #88
Opened 2021-04-22 22:48 UTC by avpotapov00

2021-04-23 08:55 UTC, rorione approved these changes
Все ок, но надо еще продумать как будет происходить замена существующей article version на обновленную, учитывая, что новые content не знают ничего о старых. Полгаю, что мы сейчас тупо удаляем article version, вложенные в нее секции и вложенный в них контент, а потом прикрепляем к article новый article version?

2021-04-23 08:55 UTC, rorione commented on backend/src/main/kotlin/com/jetbrains/life_science/article/content/master/service/ContentServiceImpl.kt
> +        contentList.forEach { content ->
Можно без 'content ->', просто заменить далее 'content' на 'it', но это дело вкуса)

2021-04-23 09:04 UTC, rorione approved these changes

2021-04-23 16:36 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/article/content/master/service/ContentServiceImpl.kt
> +        contentList.forEach { content ->
Если лямбда простая, по типу it + 1 - это хорошая практика, однако если там несколько строк, хорошая практика это явно показывать что это за переменная

2021-04-24 12:36 UTC, andrey-star requested changes
Улучшить нейминг `master` (может publish), сделать OperationDenied менее общей

2021-04-24 12:36 UTC, andrey-star commented on backend/src/main/kotlin/com/jetbrains/life_science/article/content/version/repository/ContentVersionRepositoryImpl.kt
> +        val query = CriteriaQuery(criteria)
`query` нельзя вынести в глобальную статик переменную? (ниже в delete тоже)

2021-04-24 12:36 UTC, andrey-star commented on backend/src/main/kotlin/com/jetbrains/life_science/article/version/service/ArticleVersionServiceImpl.kt
> +                throw OperationDeniedException("Version is already published")
В принципе в апруве и так published версии ничего страшного нет, не уверен, стоит ли на юзера ругаться

2021-04-24 12:36 UTC, andrey-star commented on backend/src/main/kotlin/com/jetbrains/life_science/article/content/master/service/ContentService.kt
> +    fun moveToMasterBySectionId(sectionId: Long)
Мне кажется, лучше название типо publishBySectionId. мастер очень гитово, плюс мы пекедж мастер использовали как место для базовой сущности

2021-04-24 12:36 UTC, andrey-star commented on backend/src/main/kotlin/com/jetbrains/life_science/article/section/service/SectionService.kt
> +    fun moveToMaster(newSections: List<Section>)
Мне кажется, лучше название типо publish

2021-04-24 12:36 UTC, andrey-star commented on backend/src/main/kotlin/com/jetbrains/life_science/article/content/master/controller/ContentController.kt
> +package com.jetbrains.life_science.article.content.master.controller
Пекедж мастер здесь означает, что это published версия?
Если так, то может лучше пекедж published. мастер мы использовали для артикл, чтобы указать базовую сущность

2021-04-24 12:36 UTC, andrey-star commented on backend/src/main/kotlin/com/jetbrains/life_science/article/content/master/dto/ContentDtoToInfoAdapter.kt
> +class ContentDtoToInfoAdapter(
Dto -> DTO

2021-04-24 12:36 UTC, andrey-star commented on backend/src/main/kotlin/com/jetbrains/life_science/article/content/master/controller/ContentController.kt
> +            throw OperationDeniedException("Content is not editable")
Мне кажется, OperationDenied слишком общая ошибка -- непонятно, какой статус код вернуть в адвайсе. В первом случае access denied, во втором какая-то другая

2021-04-24 12:48 UTC, avpotapov00 commented on backend/src/main/kotlin/com/jetbrains/life_science/article/content/version/repository/ContentVersionRepositoryImpl.kt
> +        val query = CriteriaQuery(criteria)
query зависит sectionId, поэтому если убирать копипасту с этого и delete методов, то только мб функцией которая сразу query вернет от id

2021-04-24 15:44 UTC, Borodin239 approved these changes
Парни уже отметили все недочёты, кроме них ничего не нашёл

2021-04-24 18:36 UTC, andrey-star approved these changes

2021-04-24 18:36 UTC, merged